# Generated by Django 5.0.6 on 2024-12-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='habit',
            name='image',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
