# Generated by Django 5.1.4 on 2024-12-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_habit_date_remove_habit_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='image',
            field=models.ImageField(default='', upload_to='Habit_image'),
        ),
    ]
